queue_rules:
  - name: default
    merge_method: squash
    conditions:
      - "label=autorelease: pending"
pull_request_rules:
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label dependencies
    conditions:
      - label = dependencies
    actions:
      merge:
  - name: Make sure PR are up to date before merging with rebase
    description: This automatically rebases PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge
      queue).
    conditions: []
    actions:
      rebase:
  - name: Automatic merge release PRs
    conditions:
      - "label=autorelease: pending"
    actions:
      merge:
        method: squash
      queue:
        name: default
merge_protections:
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"
  - name: Do not merge outdated PRs
    description: Make sure PRs are almost up to date before merging
    if:
      - base = main
    success_conditions:
      - "#commits-behind <= 10"
